# Generated by Django 4.0.3 on 2022-07-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='status_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='status_delete',
            field=models.BooleanField(default=False),
        ),
    ]
